### ISSUE TITLE
Installation of AUR package fails due to sha256sums validation error on amdgpu-pro-17.50-511655.tar.xz

### ISSUE THREAD

**Issue by enzomich** [grmat/opencl-amd#3]
Here's the final part of the installation log:

```
[...]
Loaded CA certificate '/etc/ssl/certs/ca-certificates.crt'
Resolving www2.ati.com (www2.ati.com)... 23.56.181.23
Connecting to www2.ati.com (www2.ati.com)|23.56.181.23|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 318509792 (304M) [application/x-tar]
Saving to: ‘amdgpu-pro-17.50-511655.tar.xz’

amdgpu-pro-17.50-511655.tar.x 100%[================================================>] 303.75M   919KB/s    in 5m 43s  

2018-03-06 16:46:04 (906 KB/s) - ‘amdgpu-pro-17.50-511655.tar.xz’ saved [318509792/318509792]

==> Validating source files with sha256sums...
    amdgpu-pro-17.50-511655.tar.xz ... FAILED
==> ERROR: One or more files did not pass the validity check!
```

EDIT: it appears that the downloaded file amdgpu-pro-17.50-511655.tar.xz is corrupted: not only does it fail the sha256sums integrity check, but it can't be recognised by `xz` or `tar tJf` . See also the thread at [https://community.amd.com/thread/223507](https://community.amd.com/thread/223507) .

On the other hand, the downloads for the version 17.40 are still available at https://support.amd.com/en-us/kb-articles/Pages/AMDGPU-PRO-Driver-for-Linux-Release-Notes.aspx . However, the filenames of the `.deb` files inside the download for the AMDGPU-Pro Driver Version 17.40 for Ubuntu 16.04.3 are different (as well as its sha256sums hash, of course), and the PKGBUILD file in the AUR package should be amended accordingly.

**Comment by grmat** [comment]
You can go back the version history for a [17.40 version of the `PKGBUILD`](https://github.com/grmat/opencl-amd/blob/3b576fc255f090d68c1d76904144d8fc80389b32/PKGBUILD), there is also a branch for the [16.40](https://github.com/grmat/opencl-amd/tree/16.40) version which some people seemingly wanted to stick with. You could choose those and call `makepkg`.

I can't reproduce the errors on downloading the current .deb, and obviously complaining about a corrupted file is not a bug but the intended handling for this case. What AUR-helper are you using? It seems like it didn't even pick up the correct file name (`...tar.x` instead of `...tar.xz`).

**Comment by enzomich** [comment]
The problem is not with your PKGBUILD but with the corrupted file on the AMD website (as I mentioned, this is also noted at [https://community.amd.com/thread/223507](https://community.amd.com/thread/223507)). But until (or unless) they fix it, it's better to stick with the version 17.40.

To access AUR I used Manjaro's Pamac, which, by itself, works fine (where do you see "...tar.x instead of ...tar.xz"?)

**Comment by grmat** [comment]
As I already said, I can't reproduce problems downloading the file. Each time I checked (last time right now), I get the valid file. It's strange because others complained about the same issue on the AUR. Have you tried without pamac, using `makepkg` on the `PKGBUILD` directly or downloading the file manually?

The thread at community.amd.com mentions 0 byte file size, you've got 300M, the actual size is >500M. I don't think they are serving a corrupt file but instead have problems with individual downloads.

As I don't think I can do anything about the issue and you already have a workaround, I'll keep this one closed.

**Comment by enzomich** [comment]
I had indeed run makepkg on the PKGBUILD directly, and the result was the same. **But**, lo and behold, today everything worked flawlessly from AUR using Pamac! Maybe they fixed the file on www2.ati.com... 

(Unfortunately I've found that opencl-amd is unsuitable for me because my GPU (HD 8870M) doesn't seem to be supported by the amdgpu driver, having architecture GCN 1.0 rather than >=1.1, so I'm stuck with the radeon driver and the OpenCL 1.1 supplied by opencl-catalyst, but that's another story).
